-- begin AGENTCHECK_REQUEST
create unique index IDX_AGENTCHECK_REQUEST_UK_NUMBER_ on AGENTCHECK_REQUEST (NUMBER_) where DELETE_TS is null ^
-- end AGENTCHECK_REQUEST
-- begin AGENTCHECK_ANSWER
alter table AGENTCHECK_ANSWER add constraint FK_AGENTCHECK_ANSWER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table AGENTCHECK_ANSWER add constraint FK_AGENTCHECK_ANSWER_ON_REQUEST foreign key (REQUEST_ID) references AGENTCHECK_REQUEST(ID)^
create unique index IDX_AGENTCHECK_ANSWER_UK_NUMBER_ on AGENTCHECK_ANSWER (NUMBER_) where DELETE_TS is null ^
create index IDX_AGENTCHECK_ANSWER_ON_USER on AGENTCHECK_ANSWER (USER_ID)^
create index IDX_AGENTCHECK_ANSWER_ON_REQUEST on AGENTCHECK_ANSWER (REQUEST_ID)^
-- end AGENTCHECK_ANSWER
-- begin AGENTCHECK_ANSWER_LINE
alter table AGENTCHECK_ANSWER_LINE add constraint FK_AGENTCHECK_ANSWER_LINE_ON_ANSWER foreign key (ANSWER_ID) references AGENTCHECK_ANSWER(ID)^
alter table AGENTCHECK_ANSWER_LINE add constraint FK_AGENTCHECK_ANSWER_LINE_ON_QUESTION foreign key (QUESTION_ID) references AGENTCHECK_QUESTION(ID)^
create index IDX_AGENTCHECK_ANSWER_LINE_ON_ANSWER on AGENTCHECK_ANSWER_LINE (ANSWER_ID)^
create index IDX_AGENTCHECK_ANSWER_LINE_ON_QUESTION on AGENTCHECK_ANSWER_LINE (QUESTION_ID)^
-- end AGENTCHECK_ANSWER_LINE
