alter table AGENTCHECK_ANSWER add constraint FK_AGENTCHECK_ANSWER_ON_REQUEST foreign key (REQUEST_ID) references AGENTCHECK_REQUEST(ID);
create unique index IDX_AGENTCHECK_ANSWER_UK_NUMBER_ on AGENTCHECK_ANSWER (NUMBER_) where DELETE_TS is null ;
create index IDX_AGENTCHECK_ANSWER_ON_REQUEST on AGENTCHECK_ANSWER (REQUEST_ID);
